//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goke.Core.Enttities
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // using Microsoft.EntityFrameworkCore;
    
    public enum Title : int
    {
        None = 0,
        Mr = 1,
        Mrs = 2,
        Miss = 3,
        Ms = 4,
        Dr = 5,
        Prof = 6,
        Pastor = 7,
        Rev = 8,
        Immam = 9
    }
}
