//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Microsoft.EntityFrameworkCore
{
    public class DbUpdateException : Exception
    {
        public DbUpdateException()
        {
        }

        public DbUpdateException(string message) : base(message)
        {
        }

        public DbUpdateException(string message, Exception innerException) : base(message, innerException)
        {
        }

        public DbUpdateException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }

    [Serializable]
    public class DbUpdateConcurrencyException : DbUpdateException
    {
        public DbUpdateConcurrencyException() : base()
        {
        }

        public DbUpdateConcurrencyException(string message) : base(message)
        {
        }

        public DbUpdateConcurrencyException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected DbUpdateConcurrencyException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}