//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace System.Text.Json
{
    public class JsonSerializer
    {
        public static string Serialize(Object type)
        {
            throw new NotImplementedException();
        }
    }
}