//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Microsoft.Extensions.Caching.Memory
{
    public class MemoryCacheEntryOptions
    {
        public MemoryCacheEntryOptions()
        {
        }

        public object SetSlidingExpiration(TimeSpan timeSpan)
        {
            throw new NotImplementedException();
        }
    }
}