//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Ark.Schools.Server.Api.Controllers
{
    public class Request
    {
        public static Form Form { get; set; }
    }

    public class Form
    {
        public IEnumerable<IFormFile> Files { get; set; }
    }

    public interface IFormFile
    {
        string Name { get; set; }
        int Length { get; set; }
        string FileName { get; set; }

        Task CopyToAsync(FileStream stream);
    }
}