//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goke.Web.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // using Microsoft.EntityFrameworkCore;
    
    public partial class BaseEntity
    {
        public BaseEntity() 
        {
    		Initialize();
        }
    	partial void Initialize();
    
        [Key]
    	[Required(ErrorMessage = "The Id is a mandatory Field.")]
    	[Display(Name = "Id")]
    	public System.Guid Id { get; set; }
        
        public  string ToRecord()
        {
            var str = $@"BaseEntity {{ 
                Id = {Id}, 
            ";
         
            OnToRecord(ref str);
    
            str += "}}";
    
            return str;
        }
    
        partial void OnToRecord(ref string str);
            
    
        string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this);
        }
    
    
    }
}
