//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goke.Web.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // using Microsoft.EntityFrameworkCore;
    
    public partial class BlogPost : BaseEntity
    {
        public BlogPost() : base()
        {
    		Initialize();
        }
    	partial void Initialize();
    
        [Required(ErrorMessage = "The Title is a mandatory Field.")]
    	[Display(Name = "Title")]
    	public string Title { get; set; }
        [Required(ErrorMessage = "The Content is a mandatory Field.")]
    	[Display(Name = "Content")]
    	public string Content { get; set; }
        [ForeignKey("Blog")]
    	[Required(ErrorMessage = "The Blog Id is a mandatory Field.")]
    	[Display(Name = "Blog")]
    	public System.Guid BlogId { get; set; }
    
        public virtual Blog Blog { get; set; }
        
        public new string ToRecord()
        {
            var str = $@"BlogPost {{ 
                {base.ToRecord()},
                Title = {Title}, 
                Content = {Content}, 
                BlogId = {BlogId}, 
                Blog = {Blog.ToRecord()},
            ";
         
            OnToRecord(ref str);
    
            str += "}}";
    
            return str;
        }
    
        partial void OnToRecord(ref string str);
            
    
        string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this);
        }
    
    
    }
}
