//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goke.Web.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // using Microsoft.EntityFrameworkCore;
    
    public partial class Follow : BaseEntity
    {
        public Follow() : base()
        {
    		Initialize();
        }
    	partial void Initialize();
    
        [ForeignKey("Followed")]
    	[Required(ErrorMessage = "The Followed Id is a mandatory Field.")]
    	[Display(Name = "Followed")]
    	public System.Guid FollowedId { get; set; }
        [ForeignKey("Follower")]
    	[Required(ErrorMessage = "The Follower Id is a mandatory Field.")]
    	[Display(Name = "Follower")]
    	public System.Guid FollowerId { get; set; }
        [Required(ErrorMessage = "The Connection Date is a mandatory Field.")]
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    	[Display(Name = "Connection Date")]
    	public System.DateTime ConnectionDate { get; set; }
    
        [InverseProperty("Followeds")]
    	public virtual Person Followed { get; set; }
        [InverseProperty("Followers")]
    	public virtual Person Follower { get; set; }
        
        public new string ToRecord()
        {
            var str = $@"Follow {{ 
                {base.ToRecord()},
                FollowedId = {FollowedId}, 
                FollowerId = {FollowerId}, 
                ConnectionDate = {ConnectionDate}, 
                Followed = {Followed.ToRecord()},
                Follower = {Follower.ToRecord()},
            ";
         
            OnToRecord(ref str);
    
            str += "}}";
    
            return str;
        }
    
        partial void OnToRecord(ref string str);
            
    
        string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this);
        }
    
    
    }
}
