//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goke.Web.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // using Microsoft.EntityFrameworkCore;
    
    public partial class NameEntity : BaseEntity
    {
        public NameEntity() : base()
        {
    		Initialize();
        }
    	partial void Initialize();
    
        [Required(ErrorMessage = "The Name is a mandatory Field.")]
    	[Display(Name = "Name")]
    	public string Name { get; set; }
        [Required(ErrorMessage = "The Description is a mandatory Field.")]
    	[Display(Name = "Description")]
    	public string Description { get; set; }
        
        public new string ToRecord()
        {
            var str = $@"NameEntity {{ 
                {base.ToRecord()},
                Name = {Name}, 
                Description = {Description}, 
            ";
         
            OnToRecord(ref str);
    
            str += "}}";
    
            return str;
        }
    
        partial void OnToRecord(ref string str);
            
    
        string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this);
        }
    
    
    }
}
