//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goke.Core.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // using Microsoft.EntityFrameworkCore;
    
    public partial class Card : BaseEntity
    {
        public Card() : base()
        {
    		Initialize();
        }
    	partial void Initialize();
    
        [Required(ErrorMessage = "The Pin is a mandatory Field.")]
    	[Display(Name = "Pin")]
    	public string Pin { get; set; }
        [Required(ErrorMessage = "The From is a mandatory Field.")]
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    	[Display(Name = "From")]
    	public System.DateTime From { get; set; }
        [Required(ErrorMessage = "The To is a mandatory Field.")]
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    	[Display(Name = "To")]
    	public System.DateTime To { get; set; }
        [Required(ErrorMessage = "The Permission is a mandatory Field.")]
    	[Display(Name = "Permission")]
    	public short Permission { get; set; }
        [ForeignKey("UserDetail")]
    	[Display(Name = "User Detail")]
    	public System.Guid? UserDetailId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        
        public override string ToRecord()
        {
            var str = $@"Card {{ 
                {base.ToRecord()},
                Pin = {Pin}, 
                From = {From}, 
                To = {To}, 
                Permission = {Permission}, 
                UserDetailId = {UserDetailId}, 
                UserDetail = {UserDetail.ToRecord()},
            ";
         
            OnToRecord(ref str);
    
            str += "}}";
    
            return str;
        }
    
        partial void OnToRecord(ref string str);
            
    
        public override string ToJson()
        {
            OnToJson();
            return System.Text.Json.JsonSerializer.Serialize(this);
        }
        partial void OnToJson();   
    
    }
}
